sonar.projectKey=alloweddependencies-fixture-maven-extensions-file
sonar.projectName=Allowed Dependencies Fixture - Maven Extensions File
sonar.projectVersion=1.0.0
sonar.sources=.mvn/extensions.xml
sonar.sourceEncoding=UTF-8
