sonar.projectKey=alloweddependencies-fixture-python-pip
sonar.projectName=Allowed Dependencies Fixture - Python pip
sonar.projectVersion=1.0.0
sonar.sources=app.py,requirements.txt,shared.txt,requirements-dev.txt,dev-requirements.txt,dev-shared.txt
sonar.sourceEncoding=UTF-8

