sonar.projectKey=alloweddependencies-fixture-maven-flattened-pom
sonar.projectName=Allowed Dependencies Fixture - Maven Flattened POM
sonar.projectVersion=1.0.0
sonar.sources=.
sonar.inclusions=.flattened-pom.xml
sonar.sourceEncoding=UTF-8

